# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Vuelos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 283)
        self.lista = QtWidgets.QLabel(Dialog)
        self.lista.setGeometry(QtCore.QRect(10, 20, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lista.setFont(font)
        self.lista.setObjectName("lista")
        self.SL_PrimeraClase = QtWidgets.QRadioButton(Dialog)
        self.SL_PrimeraClase.setGeometry(QtCore.QRect(30, 60, 82, 17))
        self.SL_PrimeraClase.setObjectName("SL_PrimeraClase")
        self.SL_ClaseNegocio = QtWidgets.QRadioButton(Dialog)
        self.SL_ClaseNegocio.setGeometry(QtCore.QRect(30, 90, 101, 17))
        self.SL_ClaseNegocio.setObjectName("SL_ClaseNegocio")
        self.SL_ClaseEconomico = QtWidgets.QRadioButton(Dialog)
        self.SL_ClaseEconomico.setGeometry(QtCore.QRect(30, 120, 101, 17))
        self.SL_ClaseEconomico.setObjectName("SL_ClaseEconomico")
        self.Texto_Output = QtWidgets.QLabel(Dialog)
        self.Texto_Output.setGeometry(QtCore.QRect(170, 170, 211, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Texto_Output.sizePolicy().hasHeightForWidth())
        self.Texto_Output.setSizePolicy(sizePolicy)
        self.Texto_Output.setText("")
        self.Texto_Output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Texto_Output.setObjectName("Texto_Output")
        self.Btn_Sleccion = QtWidgets.QPushButton(Dialog)
        self.Btn_Sleccion.setGeometry(QtCore.QRect(30, 180, 91, 31))
        self.Btn_Sleccion.setObjectName("Btn_Sleccion")
        self.Texto_Info = QtWidgets.QLabel(Dialog)
        self.Texto_Info.setGeometry(QtCore.QRect(180, 60, 201, 71))
        self.Texto_Info.setText("")
        self.Texto_Info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Texto_Info.setObjectName("Texto_Info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Seleccion de Vuelo"))
        self.lista.setText(_translate("Dialog", "Escoja la clase del vuelo: "))
        self.SL_PrimeraClase.setText(_translate("Dialog", "Primera clase"))
        self.SL_ClaseNegocio.setText(_translate("Dialog", "Clase de Negocio"))
        self.SL_ClaseEconomico.setText(_translate("Dialog", "Clase Econimico"))
        self.Btn_Sleccion.setText(_translate("Dialog", "Seleccionar"))
