# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CopiarPegar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 263)
        self.BotonCopiar = QtWidgets.QPushButton(Dialog)
        self.BotonCopiar.setGeometry(QtCore.QRect(60, 200, 91, 31))
        self.BotonCopiar.setObjectName("BotonCopiar")
        self.BotonPegar = QtWidgets.QPushButton(Dialog)
        self.BotonPegar.setGeometry(QtCore.QRect(240, 200, 91, 31))
        self.BotonPegar.setObjectName("BotonPegar")
        self.TextoInput = QtWidgets.QTextEdit(Dialog)
        self.TextoInput.setGeometry(QtCore.QRect(20, 10, 161, 171))
        self.TextoInput.setObjectName("TextoInput")
        self.TextoOutput = QtWidgets.QTextEdit(Dialog)
        self.TextoOutput.setGeometry(QtCore.QRect(200, 10, 161, 171))
        self.TextoOutput.setObjectName("TextoOutput")

        self.retranslateUi(Dialog)
        self.BotonCopiar.pressed.connect(self.TextoInput.selectAll) # type: ignore
        self.BotonCopiar.released.connect(self.TextoInput.copy) # type: ignore
        self.BotonPegar.pressed.connect(self.TextoOutput.clear) # type: ignore
        self.BotonPegar.released.connect(self.TextoOutput.paste) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Copy/Paste"))
        self.BotonCopiar.setText(_translate("Dialog", "Copiar"))
        self.BotonPegar.setText(_translate("Dialog", "Pegar"))
