# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pizzeria_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(284, 288)
        self.Precio_label = QtWidgets.QLabel(Dialog)
        self.Precio_label.setGeometry(QtCore.QRect(50, 30, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.Precio_label.setFont(font)
        self.Precio_label.setObjectName("Precio_label")
        self.Seleccion_label = QtWidgets.QLabel(Dialog)
        self.Seleccion_label.setGeometry(QtCore.QRect(20, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.Seleccion_label.setFont(font)
        self.Seleccion_label.setObjectName("Seleccion_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 100, 91, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.CasillaIzquierda = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.CasillaIzquierda.setContentsMargins(0, 0, 0, 0)
        self.CasillaIzquierda.setObjectName("CasillaIzquierda")
        self.Pina = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pina.setFont(font)
        self.Pina.setObjectName("Pina")
        self.CasillaIzquierda.addWidget(self.Pina)
        self.CarnesFrias = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CarnesFrias.setObjectName("CarnesFrias")
        self.CasillaIzquierda.addWidget(self.CarnesFrias)
        self.Peperoni = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.Peperoni.setObjectName("Peperoni")
        self.CasillaIzquierda.addWidget(self.Peperoni)
        self.Costo_label = QtWidgets.QLabel(Dialog)
        self.Costo_label.setGeometry(QtCore.QRect(34, 228, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Costo_label.setFont(font)
        self.Costo_label.setObjectName("Costo_label")
        self.Precio_Output = QtWidgets.QLabel(Dialog)
        self.Precio_Output.setGeometry(QtCore.QRect(150, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Precio_Output.setFont(font)
        self.Precio_Output.setText("")
        self.Precio_Output.setObjectName("Precio_Output")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 100, 91, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.CasillDerecha = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.CasillDerecha.setContentsMargins(0, 0, 0, 0)
        self.CasillDerecha.setObjectName("CasillDerecha")
        self.Queso = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Queso.setObjectName("Queso")
        self.CasillDerecha.addWidget(self.Queso)
        self.Champinion = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Champinion.setObjectName("Champinion")
        self.CasillDerecha.addWidget(self.Champinion)
        self.Atun = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Atun.setObjectName("Atun")
        self.CasillDerecha.addWidget(self.Atun)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pizzeria"))
        self.Precio_label.setText(_translate("Dialog", "Precio Pizza: $15 USD"))
        self.Seleccion_label.setText(_translate("Dialog", "Selecciona Extras:"))
        self.Pina.setText(_translate("Dialog", "Piña"))
        self.CarnesFrias.setText(_translate("Dialog", "Carnes Frias"))
        self.Peperoni.setText(_translate("Dialog", "Peperoni"))
        self.Costo_label.setText(_translate("Dialog", "Costo Total:"))
        self.Queso.setText(_translate("Dialog", "+ Queso"))
        self.Champinion.setText(_translate("Dialog", "Champiñones"))
        self.Atun.setText(_translate("Dialog", "Atun"))
