# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Programa_Saludo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(314, 207)
        self.lbl_EscribaNombre = QtWidgets.QLabel(Dialog)
        self.lbl_EscribaNombre.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.lbl_EscribaNombre.setObjectName("lbl_EscribaNombre")
        self.ln_CuadroTextoInput = QtWidgets.QLineEdit(Dialog)
        self.ln_CuadroTextoInput.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.ln_CuadroTextoInput.setObjectName("ln_CuadroTextoInput")
        self.pb_BotonEjecucion = QtWidgets.QPushButton(Dialog)
        self.pb_BotonEjecucion.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.pb_BotonEjecucion.setObjectName("pb_BotonEjecucion")
        self.lbl_TextoMostrar = QtWidgets.QLabel(Dialog)
        self.lbl_TextoMostrar.setGeometry(QtCore.QRect(20, 120, 121, 51))
        self.lbl_TextoMostrar.setText("")
        self.lbl_TextoMostrar.setObjectName("lbl_TextoMostrar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Saludo Usuario"))
        self.lbl_EscribaNombre.setText(_translate("Dialog", "Escriba su Nombre:"))
        self.pb_BotonEjecucion.setText(_translate("Dialog", "Saludar"))
