# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(351, 291)
        Dialog.setAccessibleName("")
        self.Suma = QtWidgets.QPushButton(Dialog)
        self.Suma.setGeometry(QtCore.QRect(60, 112, 91, 31))
        self.Suma.setObjectName("Suma")
        self.multiply = QtWidgets.QPushButton(Dialog)
        self.multiply.setGeometry(QtCore.QRect(190, 110, 91, 31))
        self.multiply.setObjectName("multiply")
        self.resta = QtWidgets.QPushButton(Dialog)
        self.resta.setGeometry(QtCore.QRect(60, 162, 91, 31))
        self.resta.setObjectName("resta")
        self.div = QtWidgets.QPushButton(Dialog)
        self.div.setGeometry(QtCore.QRect(190, 160, 91, 31))
        self.div.setObjectName("div")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(17, 30, 291, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(48)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.Var1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Var1.setObjectName("Var1")
        self.horizontalLayout.addWidget(self.Var1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(18, 70, 291, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(34)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Var2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Var2.setObjectName("Var2")
        self.horizontalLayout_2.addWidget(self.Var2)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 230, 193, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Result_Output = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Result_Output.setObjectName("Result_Output")
        self.horizontalLayout_3.addWidget(self.Result_Output)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.Suma.setText(_translate("Dialog", "+"))
        self.multiply.setText(_translate("Dialog", "x"))
        self.resta.setText(_translate("Dialog", "-"))
        self.div.setText(_translate("Dialog", "/"))
        self.label_1.setText(_translate("Dialog", "Ingresa el primer numero: "))
        self.label_2.setText(_translate("Dialog", "Ingresa el segundo numero: "))
        self.label_3.setText(_translate("Dialog", "Resultado:"))
